In [1]:
import numpy as np
import cv2



In [41]:
face_cascade = cv2.CascadeClassifier(#pathtofile /haarcascade_frontalface_default.xml)
 
image = cv2.imread(#pathtoimage)
grayImage = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(grayImage,1.2,3) 

In [42]:
faces

array([[ 72,  54,  63,  63],
       [252,  78,  55,  55],
       [140,  89,  48,  48],
       [334, 137,  54,  54],
       [185,  66,  58,  58]], dtype=int32)

In [43]:

print (type(faces))
print (faces)
print (faces.shape)
print ("Number of faces detected: " + str(faces.shape[0]))
 
for (x,y,w,h) in faces:
    cv2.rectangle(image,(x,y),(x+w,y+h),(0,255,0),1)
 

<class 'numpy.ndarray'>
[[ 72  54  63  63]
 [252  78  55  55]
 [140  89  48  48]
 [334 137  54  54]
 [185  66  58  58]]
(5, 4)
Number of faces detected: 5


In [44]:
grayImage

array([[141, 142, 142, ..., 140, 137, 137],
       [145, 143, 141, ..., 136, 137, 137],
       [157, 153, 148, ..., 131, 146, 146],
       ..., 
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], dtype=uint8)

In [45]:
cv2.rectangle(image, ((0,image.shape[0] -25)),(270, image.shape[0]), (255,255,255), -1)
#cv2.putText(image, "Number of faces detected: " + str(faces.shape[0]), (0,image.shape[0] -10), cv2.FONT_HERSHEY_TRIPLEX, 0.5,  (0,0,0), 1)
imS = cv2.resize(image, (960, 540)) 
cv2.imshow('Image with faces',imS)
cv2.waitKey()
cv2.destroyAllWindows()